# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
#from google.protobuf import descriptor_pb2
_ERRORCODE = descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='MVStorePB.ErrorCode',
  filename='ErrorCode',
  values=[
    descriptor.EnumValueDescriptor(
      name='RC_NOTFOUND', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_ALREADYEXISTS', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_INTERNAL', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_NOACCESS', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_NORESOURCES', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_FULL', index=5, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_DEVICEERR', index=6, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_DATAERROR', index=7, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_EOF', index=8, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_TIMEOUT', index=9, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_REPEAT', index=10, number=11,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_CORRUPTED', index=11, number=12,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_CANCELED', index=12, number=13,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_VERSION', index=13, number=14,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_TRUE', index=14, number=15,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_FALSE', index=15, number=16,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_TYPE', index=16, number=17,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_DIV0', index=17, number=18,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_INVPARAM', index=18, number=19,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_READTX', index=19, number=20,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_OTHER', index=20, number=21,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_DEADLOCK', index=21, number=22,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_QUOTA', index=22, number=23,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_SHUTDOWN', index=23, number=24,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_DELETED', index=24, number=25,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_CLOSED', index=25, number=26,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_READONLY', index=26, number=27,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_NOSESSION', index=27, number=28,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_INVOP', index=28, number=29,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RC_SYNTAX', index=29, number=30,
      options=None,
      type=None),
  ],
  options=None,
)


_SPECPROP = descriptor.EnumDescriptor(
  name='SpecProp',
  full_name='MVStorePB.SpecProp',
  filename='SpecProp',
  values=[
    descriptor.EnumValueDescriptor(
      name='SP_PINID', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_DOCUMENT', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_PARENT', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_VALUE', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_CREATED', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_CREATEDBY', index=5, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_UPDATED', index=6, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_UPDATEDBY', index=7, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_ACL', index=8, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_URI', index=9, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_STAMP', index=10, number=11,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_CLASSID', index=11, number=12,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_PREDICATE', index=12, number=13,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_NINSTANCES', index=13, number=14,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_NDINSTANCES', index=14, number=15,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_SUBCLASSES', index=15, number=16,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_SUPERCLASSES', index=16, number=17,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_CLASS_INFO', index=17, number=18,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_INDEX_INFO', index=18, number=19,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_PROPERTIES', index=19, number=20,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_JOIN_TRIGGER', index=20, number=21,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_UPDATE_TRIGGER', index=21, number=22,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_LEAVE_TRIGGER', index=22, number=23,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_REFID', index=23, number=24,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_KEY', index=24, number=25,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_VERSION', index=25, number=26,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_WEIGHT', index=26, number=27,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_PROTOTYPE', index=27, number=28,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_WINDOW', index=28, number=29,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SP_MAX', index=29, number=255,
      options=None,
      type=None),
  ],
  options=None,
)


_SPECEID = descriptor.EnumDescriptor(
  name='SpecEID',
  full_name='MVStorePB.SpecEID',
  filename='SpecEID',
  values=[
    descriptor.EnumValueDescriptor(
      name='EID_COLLECTION', index=0, number=-1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EID_LAST_ELEMENT', index=1, number=-2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EID_FIRST_ELEMENT', index=2, number=-3,
      options=None,
      type=None),
  ],
  options=None,
)


_OPMODE = descriptor.EnumDescriptor(
  name='OpMode',
  full_name='MVStorePB.OpMode',
  filename='OpMode',
  values=[
    descriptor.EnumValueDescriptor(
      name='OM_PURGE', index=0, number=262144,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OM_CHECK_STAMP', index=1, number=2097152,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OM_PURGE_IDS', index=2, number=1048576,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OM_ALL_WORDS', index=3, number=4194304,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OM_DELETED', index=4, number=16777216,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OM_FOR_UPDATE', index=5, number=33554432,
      options=None,
      type=None),
  ],
  options=None,
)


_PINFLAGS = descriptor.EnumDescriptor(
  name='PINFlags',
  full_name='MVStorePB.PINFlags',
  filename='PINFlags',
  values=[
    descriptor.EnumValueDescriptor(
      name='PF_NO_REPLICATION', index=0, number=1073741824,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PF_NO_INDEX', index=1, number=536870912,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PF_NOTIFY', index=2, number=268435456,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PF_REPLICATED', index=3, number=134217728,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PF_HIDDEN', index=4, number=67108864,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PF_READONLY', index=5, number=33554432,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PF_DELETED', index=6, number=16777216,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PF_CLASS', index=7, number=8388608,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PF_TRANSFORMED', index=8, number=4194304,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PF_PROJECTED', index=9, number=2097152,
      options=None,
      type=None),
  ],
  options=None,
)


_METAPROPS = descriptor.EnumDescriptor(
  name='MetaProps',
  full_name='MVStorePB.MetaProps',
  filename='MetaProps',
  values=[
    descriptor.EnumValueDescriptor(
      name='META_PART', index=0, number=128,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='META_NOFTINDEX', index=1, number=128,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='META_EVAL', index=2, number=128,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='META_SSTORAGE', index=3, number=64,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='META_RACCESS', index=4, number=64,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='META_NONOTIFICATION', index=5, number=32,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='META_INHERIT', index=6, number=16,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='META_IFEXIST', index=7, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='META_IFNOTEXIST', index=8, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='META_DERIVED', index=9, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='META_STOPWORDS', index=10, number=2,
      options=None,
      type=None),
  ],
  options=None,
)


_ACLPERMISSIONS = descriptor.EnumDescriptor(
  name='ACLPermissions',
  full_name='MVStorePB.ACLPermissions',
  filename='ACLPermissions',
  values=[
    descriptor.EnumValueDescriptor(
      name='ACLP_READ', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACLP_WRITE', index=1, number=2,
      options=None,
      type=None),
  ],
  options=None,
)


_CLASSFLAGS = descriptor.EnumDescriptor(
  name='ClassFlags',
  full_name='MVStorePB.ClassFlags',
  filename='ClassFlags',
  values=[
    descriptor.EnumValueDescriptor(
      name='CF_SDELETE', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CF_VIEW', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CF_CLUSTERED', index=2, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CF_INDEXED', index=3, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CF_UNIQUE', index=4, number=16,
      options=None,
      type=None),
  ],
  options=None,
)


_RETURNTYPE = descriptor.EnumDescriptor(
  name='ReturnType',
  full_name='MVStorePB.ReturnType',
  filename='ReturnType',
  values=[
    descriptor.EnumValueDescriptor(
      name='RT_PINS', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RT_COUNT', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RT_PIDS', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RT_SRCPINS', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RT_VALUES', index=4, number=5,
      options=None,
      type=None),
  ],
  options=None,
)


RC_NOTFOUND = 1
RC_ALREADYEXISTS = 2
RC_INTERNAL = 3
RC_NOACCESS = 4
RC_NORESOURCES = 5
RC_FULL = 6
RC_DEVICEERR = 7
RC_DATAERROR = 8
RC_EOF = 9
RC_TIMEOUT = 10
RC_REPEAT = 11
RC_CORRUPTED = 12
RC_CANCELED = 13
RC_VERSION = 14
RC_TRUE = 15
RC_FALSE = 16
RC_TYPE = 17
RC_DIV0 = 18
RC_INVPARAM = 19
RC_READTX = 20
RC_OTHER = 21
RC_DEADLOCK = 22
RC_QUOTA = 23
RC_SHUTDOWN = 24
RC_DELETED = 25
RC_CLOSED = 26
RC_READONLY = 27
RC_NOSESSION = 28
RC_INVOP = 29
RC_SYNTAX = 30
SP_PINID = 1
SP_DOCUMENT = 2
SP_PARENT = 3
SP_VALUE = 4
SP_CREATED = 5
SP_CREATEDBY = 6
SP_UPDATED = 7
SP_UPDATEDBY = 8
SP_ACL = 9
SP_URI = 10
SP_STAMP = 11
SP_CLASSID = 12
SP_PREDICATE = 13
SP_NINSTANCES = 14
SP_NDINSTANCES = 15
SP_SUBCLASSES = 16
SP_SUPERCLASSES = 17
SP_CLASS_INFO = 18
SP_INDEX_INFO = 19
SP_PROPERTIES = 20
SP_JOIN_TRIGGER = 21
SP_UPDATE_TRIGGER = 22
SP_LEAVE_TRIGGER = 23
SP_REFID = 24
SP_KEY = 25
SP_VERSION = 26
SP_WEIGHT = 27
SP_PROTOTYPE = 28
SP_WINDOW = 29
SP_MAX = 255
EID_COLLECTION = -1
EID_LAST_ELEMENT = -2
EID_FIRST_ELEMENT = -3
OM_PURGE = 262144
OM_CHECK_STAMP = 2097152
OM_PURGE_IDS = 1048576
OM_ALL_WORDS = 4194304
OM_DELETED = 16777216
OM_FOR_UPDATE = 33554432
PF_NO_REPLICATION = 1073741824
PF_NO_INDEX = 536870912
PF_NOTIFY = 268435456
PF_REPLICATED = 134217728
PF_HIDDEN = 67108864
PF_READONLY = 33554432
PF_DELETED = 16777216
PF_CLASS = 8388608
PF_TRANSFORMED = 4194304
PF_PROJECTED = 2097152
META_PART = 128
META_NOFTINDEX = 128
META_EVAL = 128
META_SSTORAGE = 64
META_RACCESS = 64
META_NONOTIFICATION = 32
META_INHERIT = 16
META_IFEXIST = 8
META_IFNOTEXIST = 4
META_DERIVED = 4
META_STOPWORDS = 2
ACLP_READ = 1
ACLP_WRITE = 2
CF_SDELETE = 1
CF_VIEW = 2
CF_CLUSTERED = 4
CF_INDEXED = 8
CF_UNIQUE = 16
RT_PINS = 1
RT_COUNT = 2
RT_PIDS = 3
RT_SRCPINS = 4
RT_VALUES = 5


_VALUE_VALUETYPE = descriptor.EnumDescriptor(
  name='ValueType',
  full_name='MVStorePB.Value.ValueType',
  filename='ValueType',
  values=[
    descriptor.EnumValueDescriptor(
      name='VT_ANY', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VT_INT', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VT_UINT', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VT_INT64', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VT_UINT64', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VT_RESERVED2', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VT_FLOAT', index=6, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VT_DOUBLE', index=7, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VT_BOOL', index=8, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VT_DATETIME', index=9, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VT_INTERVAL', index=10, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VT_URIID', index=11, number=11,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VT_IDENTITY', index=12, number=12,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VT_STRING', index=13, number=13,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VT_BSTR', index=14, number=14,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VT_URL', index=15, number=15,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VT_RESERVED1', index=16, number=16,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VT_REFID', index=17, number=18,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VT_REFIDPROP', index=18, number=20,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VT_REFIDELT', index=19, number=22,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VT_EXPR', index=20, number=23,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VT_QUERY', index=21, number=24,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VT_ARRAY', index=22, number=25,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VT_STRUCT', index=23, number=27,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VT_RANGE', index=24, number=28,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VT_CURRENT', index=25, number=30,
      options=None,
      type=None),
  ],
  options=None,
)

_VALUE_MODOP = descriptor.EnumDescriptor(
  name='ModOp',
  full_name='MVStorePB.Value.ModOp',
  filename='ModOp',
  values=[
    descriptor.EnumValueDescriptor(
      name='OP_SET', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_ADD', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_ADD_BEFORE', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_MOVE', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_MOVE_BEFORE', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_DELETE', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_EDIT', index=6, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_RENAME', index=7, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_PLUS', index=8, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_MINUS', index=9, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_MUL', index=10, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_DIV', index=11, number=11,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_MOD', index=12, number=12,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_NEG', index=13, number=13,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_NOT', index=14, number=14,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_AND', index=15, number=15,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_OR', index=16, number=16,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_XOR', index=17, number=17,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_LSHIFT', index=18, number=18,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_RSHIFT', index=19, number=19,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_MIN', index=20, number=20,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_MAX', index=21, number=21,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_ABS', index=22, number=22,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_LN', index=23, number=23,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_EXP', index=24, number=24,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_POW', index=25, number=25,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_SQRT', index=26, number=26,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_FLOOR', index=27, number=27,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_CEIL', index=28, number=28,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_CONCAT', index=29, number=29,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_LOWER', index=30, number=30,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_UPPER', index=31, number=31,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_TONUM', index=32, number=32,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_TOINUM', index=33, number=33,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_CAST', index=34, number=34,
      options=None,
      type=None),
  ],
  options=None,
)

_MVSTREAM_MODOP = descriptor.EnumDescriptor(
  name='MODOP',
  full_name='MVStorePB.MVStream.MODOP',
  filename='MODOP',
  values=[
    descriptor.EnumValueDescriptor(
      name='OP_INSERT', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_UPDATE', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_DELETE', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_COPY', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OP_UNDELETE', index=4, number=4,
      options=None,
      type=None),
  ],
  options=None,
)

_MVSTREAM_TXOP = descriptor.EnumDescriptor(
  name='TXOP',
  full_name='MVStorePB.MVStream.TXOP',
  filename='TXOP',
  values=[
    descriptor.EnumValueDescriptor(
      name='TX_START', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TX_COMMIT', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TX_COMMIT_ALL', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TX_ROLLBACK', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TX_ROLLBACK_ALL', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TX_START_READONLY', index=5, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TX_START_CLASSMODIFY', index=6, number=7,
      options=None,
      type=None),
  ],
  options=None,
)


_PID = descriptor.Descriptor(
  name='PID',
  full_name='MVStorePB.PID',
  filename='mvstore.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='MVStorePB.PID.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ident', full_name='MVStorePB.PID.ident', index=1,
      number=2, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REF = descriptor.Descriptor(
  name='Ref',
  full_name='MVStorePB.Ref',
  filename='mvstore.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='MVStorePB.Ref.id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='property', full_name='MVStorePB.Ref.property', index=1,
      number=2, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='eid', full_name='MVStorePB.Ref.eid', index=2,
      number=3, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='vid', full_name='MVStorePB.Ref.vid', index=3,
      number=4, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_VALUE_STREDIT = descriptor.Descriptor(
  name='StrEdit',
  full_name='MVStorePB.Value.StrEdit',
  filename='mvstore.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='str', full_name='MVStorePB.Value.StrEdit.str', index=0,
      number=1, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bstr', full_name='MVStorePB.Value.StrEdit.bstr', index=1,
      number=2, type=12, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='length', full_name='MVStorePB.Value.StrEdit.length', index=2,
      number=3, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='offset', full_name='MVStorePB.Value.StrEdit.offset', index=3,
      number=4, type=4, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_VALUE_VARRAY = descriptor.Descriptor(
  name='VArray',
  full_name='MVStorePB.Value.VArray',
  filename='mvstore.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='l', full_name='MVStorePB.Value.VArray.l', index=0,
      number=1, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='v', full_name='MVStorePB.Value.VArray.v', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_VALUE = descriptor.Descriptor(
  name='Value',
  full_name='MVStorePB.Value',
  filename='mvstore.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='MVStorePB.Value.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='property', full_name='MVStorePB.Value.property', index=1,
      number=2, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='str', full_name='MVStorePB.Value.str', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bstr', full_name='MVStorePB.Value.bstr', index=3,
      number=4, type=12, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='i', full_name='MVStorePB.Value.i', index=4,
      number=5, type=17, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ui', full_name='MVStorePB.Value.ui', index=5,
      number=6, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='i64', full_name='MVStorePB.Value.i64', index=6,
      number=7, type=18, cpp_type=2, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ui64', full_name='MVStorePB.Value.ui64', index=7,
      number=8, type=4, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='f', full_name='MVStorePB.Value.f', index=8,
      number=9, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='d', full_name='MVStorePB.Value.d', index=9,
      number=10, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='datetime', full_name='MVStorePB.Value.datetime', index=10,
      number=11, type=6, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='interval', full_name='MVStorePB.Value.interval', index=11,
      number=12, type=16, cpp_type=2, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id', full_name='MVStorePB.Value.id', index=12,
      number=13, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='varray', full_name='MVStorePB.Value.varray', index=13,
      number=14, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ref', full_name='MVStorePB.Value.ref', index=14,
      number=15, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='b', full_name='MVStorePB.Value.b', index=15,
      number=16, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='op', full_name='MVStorePB.Value.op', index=16,
      number=17, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='eid', full_name='MVStorePB.Value.eid', index=17,
      number=18, type=13, cpp_type=3, label=1,
      default_value=4294967295,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='meta', full_name='MVStorePB.Value.meta', index=18,
      number=19, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='edit', full_name='MVStorePB.Value.edit', index=19,
      number=20, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='units', full_name='MVStorePB.Value.units', index=20,
      number=21, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cid', full_name='MVStorePB.Value.cid', index=21,
      number=128, type=4, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _VALUE_VALUETYPE,
    _VALUE_MODOP,
  ],
  options=None)


_MVSTREAM_STRINGMAP = descriptor.Descriptor(
  name='StringMap',
  full_name='MVStorePB.MVStream.StringMap',
  filename='mvstore.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='str', full_name='MVStorePB.MVStream.StringMap.str', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id', full_name='MVStorePB.MVStream.StringMap.id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_MVSTREAM_RESULT = descriptor.Descriptor(
  name='Result',
  full_name='MVStorePB.MVStream.Result',
  filename='mvstore.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='cid', full_name='MVStorePB.MVStream.Result.cid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error', full_name='MVStorePB.MVStream.Result.error', index=1,
      number=2, type=14, cpp_type=8, label=1,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='count', full_name='MVStorePB.MVStream.Result.count', index=2,
      number=3, type=4, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='op', full_name='MVStorePB.MVStream.Result.op', index=3,
      number=4, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_MVSTREAM_PATHSQL = descriptor.Descriptor(
  name='PathSQL',
  full_name='MVStorePB.MVStream.PathSQL',
  filename='mvstore.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sq', full_name='MVStorePB.MVStream.PathSQL.sq', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cid', full_name='MVStorePB.MVStream.PathSQL.cid', index=1,
      number=2, type=4, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='rtt', full_name='MVStorePB.MVStream.PathSQL.rtt', index=2,
      number=3, type=14, cpp_type=8, label=1,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='uids', full_name='MVStorePB.MVStream.PathSQL.uids', index=3,
      number=4, type=13, cpp_type=3, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='params', full_name='MVStorePB.MVStream.PathSQL.params', index=4,
      number=5, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='limit', full_name='MVStorePB.MVStream.PathSQL.limit', index=5,
      number=6, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='offset', full_name='MVStorePB.MVStream.PathSQL.offset', index=6,
      number=7, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mode', full_name='MVStorePB.MVStream.PathSQL.mode', index=7,
      number=8, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='abortOnError', full_name='MVStorePB.MVStream.PathSQL.abortOnError', index=8,
      number=9, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_MVSTREAM_PIN = descriptor.Descriptor(
  name='PIN',
  full_name='MVStorePB.MVStream.PIN',
  filename='mvstore.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='op', full_name='MVStorePB.MVStream.PIN.op', index=0,
      number=1, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id', full_name='MVStorePB.MVStream.PIN.id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mode', full_name='MVStorePB.MVStream.PIN.mode', index=2,
      number=3, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stamp', full_name='MVStorePB.MVStream.PIN.stamp', index=3,
      number=4, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='nValues', full_name='MVStorePB.MVStream.PIN.nValues', index=4,
      number=5, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='values', full_name='MVStorePB.MVStream.PIN.values', index=5,
      number=6, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cid', full_name='MVStorePB.MVStream.PIN.cid', index=6,
      number=7, type=4, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='rtt', full_name='MVStorePB.MVStream.PIN.rtt', index=7,
      number=8, type=14, cpp_type=8, label=1,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_MVSTREAM_COMPOUND = descriptor.Descriptor(
  name='Compound',
  full_name='MVStorePB.MVStream.Compound',
  filename='mvstore.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='nPINs', full_name='MVStorePB.MVStream.Compound.nPINs', index=0,
      number=1, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pins', full_name='MVStorePB.MVStream.Compound.pins', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cid', full_name='MVStorePB.MVStream.Compound.cid', index=2,
      number=3, type=4, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_MVSTREAM_STATUS = descriptor.Descriptor(
  name='Status',
  full_name='MVStorePB.MVStream.Status',
  filename='mvstore.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='code', full_name='MVStorePB.MVStream.Status.code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cid', full_name='MVStorePB.MVStream.Status.cid', index=1,
      number=2, type=4, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_MVSTREAM_RESERVEDPAGES = descriptor.Descriptor(
  name='ReservedPages',
  full_name='MVStorePB.MVStream.ReservedPages',
  filename='mvstore.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='pageID', full_name='MVStorePB.MVStream.ReservedPages.pageID', index=0,
      number=1, type=13, cpp_type=3, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_MVSTREAM = descriptor.Descriptor(
  name='MVStream',
  full_name='MVStorePB.MVStream',
  filename='mvstore.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='owner', full_name='MVStorePB.MVStream.owner', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='storeID', full_name='MVStorePB.MVStream.storeID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pins', full_name='MVStorePB.MVStream.pins', index=2,
      number=3, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='properties', full_name='MVStorePB.MVStream.properties', index=3,
      number=4, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='identities', full_name='MVStorePB.MVStream.identities', index=4,
      number=5, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stmt', full_name='MVStorePB.MVStream.stmt', index=5,
      number=6, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='txop', full_name='MVStorePB.MVStream.txop', index=6,
      number=7, type=14, cpp_type=8, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='result', full_name='MVStorePB.MVStream.result', index=7,
      number=8, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='compound', full_name='MVStorePB.MVStream.compound', index=8,
      number=9, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='MVStorePB.MVStream.status', index=9,
      number=10, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flush', full_name='MVStorePB.MVStream.flush', index=10,
      number=11, type=13, cpp_type=3, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='resPages', full_name='MVStorePB.MVStream.resPages', index=11,
      number=12, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='values', full_name='MVStorePB.MVStream.values', index=12,
      number=13, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _MVSTREAM_MODOP,
    _MVSTREAM_TXOP,
  ],
  options=None)


_REF.fields_by_name['id'].message_type = _PID
_VALUE_VARRAY.fields_by_name['v'].message_type = _VALUE
_VALUE.fields_by_name['type'].enum_type = _VALUE_VALUETYPE
_VALUE.fields_by_name['id'].message_type = _PID
_VALUE.fields_by_name['varray'].message_type = _VALUE_VARRAY
_VALUE.fields_by_name['ref'].message_type = _REF
_VALUE.fields_by_name['op'].enum_type = _VALUE_MODOP
_VALUE.fields_by_name['edit'].message_type = _VALUE_STREDIT
_MVSTREAM_RESULT.fields_by_name['error'].enum_type = _ERRORCODE
_MVSTREAM_RESULT.fields_by_name['op'].enum_type = _MVSTREAM_MODOP
_MVSTREAM_PATHSQL.fields_by_name['rtt'].enum_type = _RETURNTYPE
_MVSTREAM_PATHSQL.fields_by_name['params'].message_type = _VALUE
_MVSTREAM_PIN.fields_by_name['op'].enum_type = _MVSTREAM_MODOP
_MVSTREAM_PIN.fields_by_name['id'].message_type = _PID
_MVSTREAM_PIN.fields_by_name['values'].message_type = _VALUE
_MVSTREAM_PIN.fields_by_name['rtt'].enum_type = _RETURNTYPE
_MVSTREAM_COMPOUND.fields_by_name['pins'].message_type = _MVSTREAM_PIN
_MVSTREAM.fields_by_name['owner'].message_type = _MVSTREAM_STRINGMAP
_MVSTREAM.fields_by_name['pins'].message_type = _MVSTREAM_PIN
_MVSTREAM.fields_by_name['properties'].message_type = _MVSTREAM_STRINGMAP
_MVSTREAM.fields_by_name['identities'].message_type = _MVSTREAM_STRINGMAP
_MVSTREAM.fields_by_name['stmt'].message_type = _MVSTREAM_PATHSQL
_MVSTREAM.fields_by_name['txop'].enum_type = _MVSTREAM_TXOP
_MVSTREAM.fields_by_name['result'].message_type = _MVSTREAM_RESULT
_MVSTREAM.fields_by_name['compound'].message_type = _MVSTREAM_COMPOUND
_MVSTREAM.fields_by_name['status'].message_type = _MVSTREAM_STATUS
_MVSTREAM.fields_by_name['resPages'].message_type = _MVSTREAM_RESERVEDPAGES
_MVSTREAM.fields_by_name['values'].message_type = _VALUE

class PID(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PID

class Ref(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REF

class Value(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class StrEdit(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _VALUE_STREDIT
  
  class VArray(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _VALUE_VARRAY
  DESCRIPTOR = _VALUE

class MVStream(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class StringMap(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MVSTREAM_STRINGMAP
  
  class Result(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MVSTREAM_RESULT
  
  class PathSQL(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MVSTREAM_PATHSQL
  
  class PIN(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MVSTREAM_PIN
  
  class Compound(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MVSTREAM_COMPOUND
  
  class Status(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MVSTREAM_STATUS
  
  class ReservedPages(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MVSTREAM_RESERVEDPAGES
  DESCRIPTOR = _MVSTREAM

